import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { type Article, loadArticles } from "./article-loader";
import { extractOutgoingSlugs } from "./backlinks";
import type { PlannedArticle } from "./compile-prompt";
import { slugify } from "./markdown-parser";

export type WriteResult = {
	slug: string;
	title: string;
	path: string;
	status: "created" | "updated" | "unchanged" | "invalid";
	detail?: string;
};

export type LintIssue = {
	kind: "duplicate-slug" | "broken-link" | "orphan" | "missing-description";
	slug: string;
	detail: string;
};

function yamlString(value: string): string {
	return JSON.stringify(value);
}

function frontmatterFor(article: {
	title: string;
	description?: string;
	categories?: string[];
}): string {
	const lines = ["---", `title: ${yamlString(article.title)}`];
	if (article.description?.trim()) {
		lines.push(`description: ${yamlString(article.description.trim())}`);
	}
	const cats = (article.categories ?? []).map((c) => c.trim()).filter(Boolean);
	if (cats.length > 0) {
		lines.push("categories:");
		for (const c of cats) lines.push(`  - ${yamlString(c)}`);
	}
	lines.push("---");
	return lines.join("\n");
}

function sanitizePlan(
	p: PlannedArticle,
): { slug: string; title: string } | null {
	const slug = slugify(p.slug || p.title || "");
	const title = (p.title || "").trim();
	if (!slug || !title) return null;
	return { slug, title };
}

/**
 * Write planned articles to wiki/<slug>.md with frontmatter.
 * Idempotent: files with identical content are left untouched (unchanged).
 */
export async function writePlannedArticles(
	wikiDir: string,
	plans: PlannedArticle[],
): Promise<WriteResult[]> {
	const out: WriteResult[] = [];
	for (const plan of plans) {
		const clean = sanitizePlan(plan);
		if (!clean || !plan.body || typeof plan.body !== "string") {
			out.push({
				slug: String(plan.slug ?? "?"),
				title: String(plan.title ?? "?"),
				path: "",
				status: "invalid",
				detail: "Missing slug, title, or body — skipped",
			});
			continue;
		}
		const description = plan.description?.trim() || undefined;
		const categories = Array.isArray(plan.categories)
			? plan.categories
					.map((c) => String(c).trim())
					.filter(Boolean)
					.slice(0, 8)
			: [];
		const fm = frontmatterFor({ title: clean.title, description, categories });
		const body = plan.body.trim().replace(/\r\n/g, "\n");
		const text = `${fm}\n\n${body}\n`;
		const path = join(wikiDir, `${clean.slug}.md`);

		let existing: string | null = null;
		try {
			existing = await readFile(path, "utf-8");
		} catch {
			existing = null;
		}
		if (existing === text) {
			out.push({
				slug: clean.slug,
				title: clean.title,
				path,
				status: "unchanged",
			});
			continue;
		}
		await writeFile(path, text, "utf-8");
		out.push({
			slug: clean.slug,
			title: clean.title,
			path,
			status: existing === null ? "created" : "updated",
		});
	}
	return out;
}

/**
 * Rebuild wiki/index.md as the system-owned master catalog.
 * Groups articles by category so the graph stays discoverable.
 * Idempotent — rewrites only when content differs.
 */
export async function rebuildIndexPage(wikiDir: string): Promise<{
	path: string;
	changed: boolean;
	count: number;
}> {
	const articles = await loadArticles(wikiDir);
	const path = join(wikiDir, "index.md");
	const others = articles.filter((a) => a.slug !== "index");

	const byCategory = new Map<string, Article[]>();
	const uncategorized: Article[] = [];
	for (const a of others) {
		const raw = a.frontmatter?.categories;
		const cats: string[] = Array.isArray(raw)
			? raw.map((c) => String(c)).filter(Boolean)
			: typeof raw === "string" && raw.trim()
				? [raw.trim()]
				: [];
		if (cats.length === 0) uncategorized.push(a);
		for (const c of cats) {
			const list = byCategory.get(c) ?? [];
			list.push(a);
			byCategory.set(c, list);
		}
	}
	const sortedCats = [...byCategory.keys()].sort((a, b) => a.localeCompare(b));
	for (const list of byCategory.values()) {
		list.sort((a, b) => a.title.localeCompare(b.title));
	}
	uncategorized.sort((a, b) => a.title.localeCompare(b.title));

	const line = (a: Article): string =>
		`- [[${a.title}]]${a.description ? ` — ${a.description}` : ""}`;

	const sections: string[] = [
		"<!-- auto-generated by `almanac compile` — do not edit by hand -->",
		"",
		`This catalog lists all ${others.length} article(s) in the vault.`,
		"",
	];
	for (const cat of sortedCats) {
		sections.push(`## ${cat}`, "");
		for (const a of byCategory.get(cat) ?? []) sections.push(line(a));
		sections.push("");
	}
	if (uncategorized.length > 0) {
		sections.push("## Uncategorized", "");
		for (const a of uncategorized) sections.push(line(a));
		sections.push("");
	}
	if (others.length === 0) {
		sections.push(
			"_No articles yet — drop source material into `raw/` and run `almanac compile`._",
			"",
		);
	}

	const fm = [
		"---",
		'title: "Index"',
		'description: "Master catalog of all articles."',
		"---",
	].join("\n");
	const text = `${fm}\n\n${sections.join("\n").trimEnd()}\n`;

	let existing: string | null = null;
	try {
		existing = await readFile(path, "utf-8");
	} catch {
		existing = null;
	}
	if (existing === text) return { path, changed: false, count: others.length };
	await writeFile(path, text, "utf-8");
	return { path, changed: true, count: others.length };
}

/** Light lint pass: duplicates, broken links, orphans, missing descriptions. */
export function lintArticles(articles: Article[]): {
	issues: LintIssue[];
	orphans: string[];
	broken: LintIssue[];
} {
	const issues: LintIssue[] = [];

	const seen = new Map<string, string>();
	for (const a of articles) {
		const first = seen.get(a.slug);
		if (first && first !== a.path) {
			issues.push({
				kind: "duplicate-slug",
				slug: a.slug,
				detail: `${first} <-> ${a.path}`,
			});
		} else {
			seen.set(a.slug, a.path);
		}
	}

	const known = new Set<string>();
	for (const a of articles) {
		known.add(a.slug);
		known.add(slugify(a.title));
		const aliases = a.frontmatter?.aliases;
		if (Array.isArray(aliases)) {
			for (const alias of aliases) {
				const s = slugify(String(alias));
				if (s) known.add(s);
			}
		}
	}
	const broken: LintIssue[] = [];
	for (const a of articles) {
		for (const target of extractOutgoingSlugs(a.content)) {
			if (!known.has(target)) {
				const issue: LintIssue = {
					kind: "broken-link",
					slug: a.slug,
					detail: `links to missing "[[${target}]]"`,
				};
				issues.push(issue);
				broken.push(issue);
			}
		}
	}

	const linked = new Set<string>();
	for (const a of articles) {
		for (const t of extractOutgoingSlugs(a.content)) linked.add(t);
	}
	const orphans: string[] = [];
	for (const a of articles) {
		if (a.slug === "index" || a.slug === "preferences") continue;
		const hasOut = ((): boolean => {
			try {
				return extractOutgoingSlugs(a.content).length > 0;
			} catch {
				return false;
			}
		})();
		const hasIn = linked.has(a.slug) || linked.has(slugify(a.title));
		if (!hasOut && !hasIn) {
			orphans.push(a.slug);
			issues.push({ kind: "orphan", slug: a.slug, detail: a.title });
		}
	}

	for (const a of articles) {
		if (a.slug === "index") continue;
		if (!a.description?.trim()) {
			issues.push({
				kind: "missing-description",
				slug: a.slug,
				detail: "No one-line description in frontmatter",
			});
		}
	}

	return { issues, orphans, broken };
}

/** Read preferences text (wiki/preferences.md) — never throws, may be empty. */
export async function loadPreferencesText(wikiDir: string): Promise<string> {
	for (const name of ["preferences.md", "Preferences.md"]) {
		try {
			const raw = await readFile(join(wikiDir, name), "utf-8");
			// Strip frontmatter title line for a cleaner prompt signal.
			return raw.replace(/^---[\s\S]*?---\s*/, "").trim();
		} catch {}
	}
	return "";
}
